### ISSUE TITLE
開発環境、本番環境などの切り分け戦略

### ISSUE THREAD

**Issue by Kota8102** [Kota8102/diary-app#15]
AWSの環境をどのようにわけるか検討して構築する。

**Comment by mt-osho-san** [comment]
利用する環境: dev, prod
　- developブランチにマージされたときにdev環境へデプロイ
　- mainブランチにマージされたときにprod環境へデプロイ
　- 現状はシンプルさを優先してステージング環境はなし
　- featureの確認はdevアカウントで行う
Gitのブランチ
　- 環境に合わせてfeature, develop, mainの３つとする
