### ISSUE TITLE
技術仕様の決定

### ISSUE THREAD

**Issue by Kota8102** [Kota8102/diary-app#3]
## 要件
技術仕様を決定する

## タスク
- [ ] アーキテクチャ図の作成

**Comment by Kota8102** [comment]
S3ホスティング

- フロントエンド
  - React

- バックエンド
  - API Gatewat + lambda(Rust) + DynamoDB

**Comment by mt-osho-san** [comment]
アーキテクチャ図作成しました。

![diary64-arch-240128 drawio](https://github.com/Kota8102/diary-app/assets/85208872/f8a978bc-1144-4c97-8cba-e23a8d415c03)
