### ISSUE TITLE
コード規約の整備

### ISSUE THREAD

**Issue by Kota8102** [Kota8102/diary-app#8]
## 要件
React + TypeScriutのESLIintを整備

**Comment by sfurukawa7** [comment]
PrettierとEslintの設定ファイルはコミット＆プッシュ完了

**Comment by sfurukawa7** [comment]
いったんこれで決まったのでclose
googleのベストプラクティスもちょっと調べてみてよければ今後いれるかも

ちょっと気になることであと決めたいこと
- [ ] `type` or `interface`
