### ISSUE TITLE
フロントエンドの設計ポリシーを決める

### ISSUE THREAD

**Issue by sfurukawa7** [Kota8102/diary-app#9]
- [x] フォルダー構成
- [x] スタイルシート（CSS、SASS、etc）

※他思いついたら随時追加します

**Comment by sfurukawa7** [comment]
フォルダー構成は何か良さげなreactリポジトリを参考にしたいです

**Comment by Kota8102** [comment]
CSSは、Tailwind CSSをメイン利用とかあり？
わんちゃん作るの楽

**Comment by sfurukawa7** [comment]
ありあり〜

**Comment by sfurukawa7** [comment]
フォルダー構造，コンポーネント以外のフォルダーは[これ](https://github.com/kriasoft/react-starter-kit/tree/main/app)参考にして，コンポーネント部分はAtomic Designの[これ](https://github.com/diegohaz/arc/tree/master)とかどうやろ

**Comment by sfurukawa7** [comment]
`feature/#9`ブランチにフォルダー構成の叩きつくってみました．
具体的には，以下のような感じ
- `src/assets`: アプリケーションのビジュアル要素を格納するためのディレクトリ。グラフィックや共通スタイルシートなど
- `src/components`: 再利用可能なUIコンポーネントが保持されるディレクトリ。Atomic Design想定ではあるがデザインのやり方に合わせて対応予定
- `src/context`: ReactのContext APIを使用してアプリケーションのステートを管理するためのファイルが含まれるディレクトリ
- `src/hooks`: カスタムフックを集約するディレクトリ。複数のコンポーネント間でビジネスロジックを共有するために使用される。
- `src/pages`: 各ページに対応するコンポーネントを含むディレクトリ
- `src/types`: TypeScriptの型定義やインターフェースを含むディレクトリ
- `src/utils`: 共通のユーティリティ関数やヘルパー関数が収められるディレクトリ

**Comment by sfurukawa7** [comment]
タスク完了したのでclose
